version: '3'

services:
  eslint:
    build: .
    working_dir: /react
    expose:
      - 8080
      - 3004
    ports:
      - "8080:8080"
      - "3004:3004"
    stdin_open: true
    volumes:
      - ./react:/react
